# -*- coding: utf-8 -*-
{
    'name': 'Gestion academica',
    'version': '17.0.1.0.1',
    'category': 'Industries',
    'summary': """sistema ERP educativo""",
    'description': """Una solución ERP completa y amigable diseñada para la 
    administración escolar es Educational ERP. Facilita la gestión de ingresos 
    de estudiantes, matrículas, registros de profesores, clases y asignaturas.""",
    'author': 'Grupo20',
    'depends': ['stock', 'hr_recruitment'],
    'data': [
        'security/education_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'wizard/application_reject_views.xml',
        'views/education_main_menu.xml',
        'views/res_partner_views.xml',
        'views/education_academic_year_views.xml',
        'views/education_application_views.xml',
        'views/education_class_views.xml',
        'views/education_class_division_views.xml',
        'views/education_student_views.xml',
        'views/education_faculty_views.xml',
        'views/education_document_views.xml',
        'views/document_document_views.xml',
        'views/education_division_views.xml',
        'views/education_subject_views.xml',
        'views/education_syllabus_views.xml',
        'views/education_amenities_views.xml',
        'views/res_company_views.xml',
        'views/hr_applicant_views.xml',
        'views/application_reject_reason_views.xml',
        'report/student_id_card_reports.xml',
        'report/student_application_reports.xml',
        'report/faculty_id_card_reports.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
