# -*- coding: utf-8 -*-
from . import application_reject_reason
from . import document_document
from . import education_academic_year
from . import education_amenties
from . import education_application
from . import education_class
from . import education_class_amenities
from . import education_class_division
from . import education_class_history
from . import education_division
from . import education_document
from . import education_faculty
from . import education_medium
from . import education_student
from . import education_subject
from . import education_syllabus
from . import hr_applicant
from . import res_company
from . import res_partner
